import type { DashboardData, EvidenceRecord } from "@/lib/dashboard-types";

const insight = (metricId: string) => `merchant-M43--${metricId}--2026-01-01--2026-02-28`;

export const MOCK_DASHBOARD: DashboardData = {
  meta: {
    merchant_key: "M43",
    date_from: "2026-01-01",
    date_to: "2026-02-28",
    timezone: "Asia/Tehran",
    source_kind: "deterministic_offline_snapshot",
    data_freshness: "2026-02-28T10:35:19+03:30",
    partial_data: true,
    calculation_version: "v1.0.0",
  },
  merchant: {
    merchant_key: "M43",
    category_id: 56_610_001,
    category_title: "کیف و کفش فروشی",
    terminal_count: 1,
  },
  kpis: [
    {
      metric_id: "verified_revenue",
      label: "درآمد تأییدشده",
      value: 23_448_530_700,
      unit: "IRR",
      evidence_id: insight("verified_revenue"),
    },
    {
      metric_id: "verified_session_rate",
      label: "نرخ تکمیل",
      value: 20_340 / 29_483,
      unit: "ratio",
      confidence_interval_95: { low: 0.6846, high: 0.6951 },
      evidence_id: insight("verified_session_rate"),
    },
    {
      metric_id: "eligible_sessions",
      label: "نشست‌های واجد شرایط",
      value: 29_483,
      unit: "sessions",
      evidence_id: insight("eligible_sessions"),
    },
    {
      metric_id: "observed_repeat_card_rate",
      label: "کارت تکراری مشاهده‌شده",
      value: 3_692 / 9_745,
      unit: "ratio",
      evidence_id: insight("observed_repeat_card_rate"),
    },
  ],
  lifecycle: {
    grain: "session",
    evidence_id: insight("payment_lifecycle_counts"),
    stages: [
      { stage: "Created", count: 29_483, dropoff_from_previous: null },
      { stage: "Attempted", count: 26_169, dropoff_from_previous: 3_314 / 29_483 },
      { stage: "InBank", count: 25_973, dropoff_from_previous: 196 / 26_169 },
      { stage: "Paid", count: 20_530, dropoff_from_previous: 5_443 / 25_973 },
      { stage: "Verified", count: 20_340, dropoff_from_previous: 190 / 20_530 },
    ],
  },
  trend: [
    { date: "ژانویه ۲۰۲۶", sessions: 10_623, verified_sessions: 7_360, verified_revenue: 8_525_828_600, conversion_rate: 0.6928362986 },
    { date: "فوریه ۲۰۲۶", sessions: 18_860, verified_sessions: 12_980, verified_revenue: 14_922_702_100, conversion_rate: 0.6882290562 },
  ],
  amount_bands: [
    { band_id: "under_1m", label_fa: "کمتر از ۱ میلیون", min_irr: 0, max_exclusive_irr: 1_000_000, sessions: 18_523, verified_sessions: 12_636, conversion_rate: 0.6821789127031258, verified_revenue: 9_528_739_480, evidence_id: insight("amount_band_performance") },
    { band_id: "1m_to_5m", label_fa: "۱ تا ۵ میلیون", min_irr: 1_000_000, max_exclusive_irr: 5_000_000, sessions: 10_674, verified_sessions: 7_479, conversion_rate: 0.7006745362563238, verified_revenue: 12_240_090_920, evidence_id: insight("amount_band_performance") },
    { band_id: "5m_to_20m", label_fa: "۵ تا ۲۰ میلیون", min_irr: 5_000_000, max_exclusive_irr: 20_000_000, sessions: 277, verified_sessions: 218, conversion_rate: 0.7870036101083032, verified_revenue: 1_538_975_800, evidence_id: insight("amount_band_performance") },
    { band_id: "20m_to_100m", label_fa: "۲۰ تا ۱۰۰ میلیون", min_irr: 20_000_000, max_exclusive_irr: 100_000_000, sessions: 8, verified_sessions: 7, conversion_rate: 0.875, verified_revenue: 140_724_500, evidence_id: insight("amount_band_performance") },
    { band_id: "100m_plus", label_fa: "۱۰۰ میلیون و بیشتر", min_irr: 100_000_000, max_exclusive_irr: null, sessions: 1, verified_sessions: 0, conversion_rate: 0, verified_revenue: 0, evidence_id: insight("amount_band_performance") },
  ],
  revenue_decomposition: {
    current: { sessions: 18_860, conversion_rate: 0.6882290562, verified_aov: 1_149_668.883, verified_revenue: 14_922_702_100 },
    previous: { sessions: 10_623, conversion_rate: 0.6928362986, verified_aov: 1_158_400.625, verified_revenue: 8_525_828_600 },
    note: "مقایسه مستقیم فوریه با ژانویه است؛ اجزا توصیفی هستند و علت تغییر را اثبات نمی‌کنند.",
  },
  retry: {
    retry_sessions: 7_922,
    retry_rate: 7_922 / 29_483,
    rescued_sessions: 6_057,
    evidence_id: insight("retry_session_rate"),
  },
  repeat: {
    observed_cards: 9_745,
    repeat_cards: 3_692,
    observed_repeat_rate: 3_692 / 9_745,
    scope: "(merchant_key, payer_card_key)",
    evidence_id: insight("observed_repeat_card_rate"),
  },
  paid_not_verified: {
    sessions: 190,
    rate: 190 / 29_483,
    evidence_id: insight("paid_not_verified_rate"),
  },
  latency: {
    p50_ms: 152,
    p90_ms: 236,
    p95_ms: 271,
    sample_size: 26_739,
    definition: "مدت فراخوانی API درگاه؛ نه زمان تعامل کاربر",
    evidence_id: insight("init_latency_p95_ms"),
  },
  psp_codes: [
    { psp_code: "PSP-03", response_code: "56", attempts: 159, evidence_id: insight("psp_code_frequency") },
    { psp_code: "PSP-03", response_code: "-3", attempts: 101 },
    { psp_code: "PSP-03", response_code: "51", attempts: 79 },
    { psp_code: "PSP-03", response_code: "59", attempts: 76 },
    { psp_code: "PSP-03", response_code: "55", attempts: 42 },
    { psp_code: "PSP-03", response_code: "54", attempts: 38 },
    { psp_code: "PSP-03", response_code: "75", attempts: 11 },
    { psp_code: "PSP-03", response_code: "84", attempts: 10 },
  ],
  psp_code_coverage: {
    eligible_psp_attempts: 34_406,
    coded_attempts: 533,
    missing_code_attempts: 33_873,
    coverage_rate: 0.015491484043480788,
    evidence_id: insight("psp_code_coverage"),
  },
  peer: {
    eligible: true,
    peer_count: 21,
    peer_median_rate: 0.6147798742138365,
    p25_rate: 0.5643372157515253,
    p75_rate: 0.6493194555644516,
    merchant_rate: 0.6898890886273445,
    gap_percentage_points: 7.5109214413508045,
  },
  opportunity: {
    value: 0,
    unit: "IRR scenario",
    is_forecast: false,
    formula: "max(0, peer_median_conversion - merchant_conversion) × eligible_sessions × merchant_verified_aov",
    evidence_id: insight("opportunity_scenario_irr"),
  },
  insights: [
    {
      insight_id: insight("retry_session_rate"),
      metric_id: "retry_session_rate",
      title: "بازیابی تلاش‌های مجدد را حفظ کنید",
      statement: "از ۷٬۹۲۲ نشست چندتلاشی، ۶٬۰۵۷ نشست در نهایت تأیید شده‌اند.",
      recommendation: "پیام ادامه پرداخت را پس از شکست نخست نگه دارید و نرخ بازیابی را هفتگی پایش کنید.",
      trigger: "۷٬۹۲۲ نشست بیش از یک تلاش داشته‌اند.",
      expected_mechanism: "حفظ مسیر ادامه پرداخت، فرصت رسیدن تلاش بعدی به Verified را نگه می‌دارد.",
      measurement_plan: "تعداد نشست‌های نجات‌یافته و نرخ تلاش مجدد را در بازه بعدی با همین تعریف مقایسه کنید.",
      confidence: "supported",
    },
    {
      insight_id: insight("paid_not_verified_rate"),
      metric_id: "paid_not_verified_rate",
      title: "شکاف Paid تا Verified را ببندید",
      statement: "۱۹۰ نشست پس از Paid به Verified نرسیده‌اند؛ ۰٫۶۴٪ از همه نشست‌ها.",
      recommendation: "callback و verify idempotent را بازبینی کنید و پیش از آزمون، هدف کاهش نسبت به خط مبنای ۰٫۶۴٪ را ثبت کنید.",
      trigger: "۱۹۰ نشست پس از Paid به Verified نرسیده‌اند.",
      expected_mechanism: "رفع وقفه callback یا verify می‌تواند نشست کسروجه‌شده را به تأیید نهایی برساند.",
      measurement_plan: "تعداد و نرخ Paid بدون Verified را پس از اصلاح با همین جمعیت مقایسه کنید.",
      confidence: "supported",
    },
    {
      insight_id: insight("observed_repeat_card_rate"),
      metric_id: "observed_repeat_card_rate",
      title: "مشتریان تکراری مشاهده‌شده را نگه دارید",
      statement: "۳٬۶۹۲ کارت از ۹٬۷۴۵ کارت مشاهده‌شده در M43 دست‌کم دو نشست تأییدشده دارند.",
      recommendation: "نرخ بازگشت همین گروه را ماهانه و فقط در دامنه پذیرنده M43 پایش کنید.",
      trigger: "۳٬۶۹۲ کارت مشاهده‌شده بیش از یک نشست Verified دارند.",
      expected_mechanism: "پیگیری همین گروه، تغییر رفتار مشاهده‌شده درون پذیرنده را آشکار می‌کند.",
      measurement_plan: "نرخ کارت تکراری مشاهده‌شده را با همان دامنه merchant_key پایش کنید.",
      confidence: "supported",
    },
  ],
  metric_registry: [
    { metric_id: "verified_revenue", label: "درآمد تأییدشده", formula: "SUM(amount) once per final Verified session", grain: "session" },
    { metric_id: "verified_session_rate", label: "نرخ تکمیل", formula: "Verified sessions / eligible sessions", grain: "session" },
    { metric_id: "retry_session_rate", label: "نرخ تلاش مجدد", formula: "sessions with attempt_count > 1 / eligible sessions", grain: "session" },
    { metric_id: "rescued_sessions", label: "نشست‌های نجات‌یافته", formula: "sessions with attempt_count > 1 and final status Verified", grain: "session" },
    { metric_id: "paid_not_verified_rate", label: "Paid بدون Verified", formula: "Paid-not-Verified sessions / eligible sessions", grain: "session" },
    { metric_id: "amount_band_performance", label: "عملکرد بازه مبلغ", formula: "Verified sessions / sessions within fixed IRR band", grain: "session" },
    { metric_id: "psp_code_coverage", label: "پوشش کد پاسخ PSP", formula: "coded eligible attempts / eligible PSP attempts", grain: "attempt" },
  ],
  adjusted_fee_notice: "Adjusted fee is a uniformly transformed analytical value and does not represent ZarinPal's actual tariff.",
};

export const MOCK_EVIDENCE_RECORDS: EvidenceRecord[] = [
  { session_key: "1223158", created_at: "2026-01-28T23:09:56+03:30", session_status: "Verified", amount: 767_300, attempt_count: 1, final_try_status: "Verified", psp_path: "PSP-03", payer_card_key: "CARD-219526" },
  { session_key: "1266911", created_at: "2026-01-28T23:10:20+03:30", session_status: "Verified", amount: 767_300, attempt_count: 1, final_try_status: "Verified", psp_path: "PSP-03", payer_card_key: "CARD-388678" },
  { session_key: "1913990", created_at: "2026-01-28T23:10:36+03:30", session_status: "Failed", amount: 767_300, attempt_count: 1, final_try_status: "InBank", psp_path: "PSP-03", payer_card_key: null },
];
